---
name: caddy
releases:
- name: caddy
  version: create
  url: file://.
  # url: https://github.com/dpb587/caddy-bosh-release
instance_groups:
- name: caddy
  jobs:
  - name: caddy
    release: caddy
    properties:
      caddyfile: |
        localhost {
          basicauth / vcap c1oudc0w
          proxy / https://httpbin.org
        }
  instances: 1
  persistent_disk: 1024
  vm_type: default
  stemcell: default
  networks:
  - name: default
  azs:
  - z1
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
